####
#### flutter_test lane
####
flutter_build_android: #Job name
  stage: build # kind of job
  before_script:
    - flutter packages get
    - flutter clean
  script:
     - flutter build apk --debug --flavor dev
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-debug.apk
  tags:
    - flutter
